services:
  - type: web
    name: content-moderation-app
    env: node
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: RENDER
        value: "true"
      - key: FRONTEND_URL
        value: "https://content-moderation-frontend.onrender.com" # Replace with your actual frontend URL
      # Add your other environment variables here, such as:
      # - key: SUPABASE_URL
      #   value: your-supabase-url
      # - key: SUPABASE_ANON_KEY
      #   value: your-supabase-anon-key
      # - key: OPENAI_API_KEY
      #   value: your-openai-api-key